module.exports.id=module.id;
module.exports.modelData = { tableName:"r_CRs", idField:"CRID",
    fields:["ChID","CRID","CRName","Notes","FinID","FacID","CRPort","CRCode","StockID","SecID","CashType","UseProdNotes",
        "SrvID","UseStockPL",
        "AutoCreateNewCheque","BaudRate","LEDType",
        "CredCardMask","MaxChange","CanEditWeightQty","CanEditPrice","CanEditProdID","CanEnterPosDiscount","PrintTextAnull",
        "PrintReport","PrintReportRet","PrintReportMonRec","PrintReportMonExp","PrintReportZ","PrintReportX","PreviewReport",
        "UseDecQtyBarcode","PaperWarning","AlwaysShowPosEditor","MaxSuspended","AskParamsAfterOpen","AskParamsBeforeClose",
        "ShowPosDisc","ShowChequeDisc","AutoSelDiscs", "AskDCardsAfterOpen","AskDCardsBeforeClose","CanEnterDCard","NoManualDCardEnter",
        "CanEnterCodeID1","CanEnterCodeID2","CanEnterCodeID3","CanEnterCodeID4","CanEnterCodeID5","CanEnterNotes",
        "ShowCancels","DecQtyFromRef","AskVisitorsAfterOpen","MixedPays","OpenMoneyBoxOnDeposit","AutoFillPays","ShowPosEditOnCancel",
        "AskPWDPeriodRep","AskPWDCnCheque","AskPWDSuspend","AskPWDBalance","AskPWDRet","AskPWDCn","AskPWDAnull","AskPWDFind","UseBarcode","AskPWDMoneyBox","AskPWDDCardFind","AskPWDDeposit",
        "CheckRetSum","CheckRetPayForms","AllowInvalidMonExp",
        "CashRegMode","NetPort","ModemID","ModemPassword",
        "PrintDiscs","PrintAfterSendOrder","ScaleID","GroupProds",
        "AllowQtyReduction","PosEmpIDType","UseEmps","PosEmpID","ChequeEmp","IP","PrintCopyForCard",
        "ZReportWarning","ZRepAfterShift","ZRepExecInTime","ZRepShiftEndTime","ZRepExecTime","ZRepShiftTimeCheck",
        "ProcessingID","UserName","UserPassword","PrintInfoAnull","AutoUpdateTaxes","ChangeSumWarning","AskPWDPosRePay","CancelMDiscsWarning",
        "CollectMetrics","MetricMaxDays","AsyncChequeInput",
        "NFOurID"]
};
